group_A_subproject/BookEntryBean/src/main/java/CDIBeans/LoginBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CDIBeans;

import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import java.io.Serializable;
import java.util.logging.Logger;
import javax.ejb.EJB;
import usermgt.UserManagementBean;

/**
 * User Login and Logout
 *
 * @author hychen39@gm.cyut.edu.tw
 */
@Named(value = "loginBean")
@SessionScoped
public class LoginBean implements Serializable {

    @EJB
    private UserManagementBean userManagementBean;

    /**
     * Creates a new instance of LoginBean
     */
    public LoginBean() {
    }
    
    public boolean isLogin(){
        return userManagementBean.isLoginStatus();
    }
    /**
     * 
     * @return 
     */
    public String getUsername(){
        Logger.getLogger(LoginBean.class.getName()).info(String.format("Login Username: %s",
                userManagementBean.getPrincipalName()));
        return userManagementBean.getPrincipalName();
    }
}

group_A_subproject/BookEntryBean/src/main/webapp/templates/globalFunctionBar.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        <ui:composition>
              <p>
                  <h:link outcome="/displayBooks" styleClass="btn btn-primary">二手書</h:link>
                  <!--<a class="btn btn-primary" data-toggle="collapse" href="" role="button" aria-expanded="false" aria-controls="collapseExample">二手書</a>-->
                <a class="btn btn-primary" data-toggle="collapses" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">物品</a>
                <a class="btn btn-primary" data-toggle="collapsess" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">共享</a>
                <a class="btn btn-primary" data-toggle="collapsesss" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">我的商品</a>
                <a class="btn btn-primary" data-toggle="collapsesss" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">尋書</a>
                </p>
        </ui:composition>
    </h:body>
</html>

group_A_subproject/BookEntryBean/src/main/webapp/templates/globalNavBar.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        <ui:composition>
            <div class="navbar navbar-expand-sm bg-dark navbar-dark">
                <div class="container-fluid p-0">
                    <!--FIXME: 網站 LOGO 尚未決定. SP3-->
                    <h:link class="navbar-brand" outcome="/index">LOGO</h:link>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#form">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse col-sm-11" id="form">
                        <form class="form-inline navbar-nav col-sm-12 p-0">
                            <p:selectOneMenu class="my-1 ml-sm-2">
                                <f:selectItem itemLabel="ISBN" itemValue="isbn" />
                                <f:selectItem itemLabel="書名" itemValue="bookName" />
                                <f:selectItem itemLabel="作者" itemValue="3" />
                            </p:selectOneMenu>
                            <!--ToDo: Input Value 的 Value Binding 未實作. hychen39 @ sp9 review-->
                            <input type="search" class="form-control my-1 mr-sm-2 col-sm-8 col-md-9"/>
                            <!--ToDo: 執行搜尋按鈕尚未實作 hychen39 @ sp9 review-->
                            <button class="fas fa-search btn btn-outline-primary my-2 my-sm-0" type="submit"></button>
                            <div id="user-info">
                                <h:link outcome="/authen/login" class="btn btn-outline-success my-1 ml-sm-2">註冊/登入</h:link>
                                <h:link outcome="/member/member" class="btn btn-outline-success my-1 ml-sm-2">會員專區</h:link>
                                <h:link outcome="/member/member" class="btn btn-outline-success my-1 ml-sm-2">收藏<i class="far fa-heart"/></h:link>
                                <span class="btn btn-outline-success my-1 ml-sm-2">  
                                     #{loginBean.username} <i class="far fa-user"></i>
                                </span>
                            </div>

                        </form>
                    </div>
                </div>
            </div>

            <div class="btn-group col px-0">
                <div class="btn-group col px-0">
                    <button type="button" 
                            class="btn btn-primary dropdown-toggle" 
                            data-toggle="dropdown">
                        二手書
                    </button>
                    <div class="dropdown-menu w-500">
                        <!--Done: 二手書項目下拉後會有各學院, 學院下有各系. 此功能獨立成一個新的 User Story. SP3 @s10635105-->
                        <table>
                            <td valign="top">
                                <a class="dropdown-item" href="#">管理學院</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#">財務金融系</a>
                                <a class="dropdown-item" href="#">企業管理系</a>
                                <a class="dropdown-item" href="#">保險金融管理系</a>
                                <a class="dropdown-item" href="#">休閒事業管理系</a>
                                <a class="dropdown-item" href="#">行銷與流通管理系所</a>
                                <a class="dropdown-item" href="#">銀髮產業管理系</a>
                            </td>
                            <td valign="top">
                                <a class="dropdown-item" href="#">理工學院</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#">營建工程系</a>
                                <a class="dropdown-item" href="#">工業工程與管理系</a>
                                <a class="dropdown-item" href="#">應用化學系</a>
                                <a class="dropdown-item" href="#">環境工程與管理系</a>
                                <a class="dropdown-item" href="#">航空機械系</a>
                            </td>
                            <td valign="top">
                                <a class="dropdown-item" href="#">設計學院</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#">建築系</a>
                                <a class="dropdown-item" href="#">工業設計系</a>
                                <a class="dropdown-item" href="#">視覺傳達設計系</a>
                                <a class="dropdown-item" href="#">景觀及都市設計系</a>
                            </td>
                            <td valign="top">
                                <a class="dropdown-item" href="#">人文暨社會學院</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#">傳播藝術系</a>
                                <a class="dropdown-item" href="#">應用英語系</a>
                                <a class="dropdown-item" href="#">幼兒保育系</a>
                                <a class="dropdown-item" href="#">社會工作系</a>    
                            </td>
                            <td valign="top">
                                <a class="dropdown-item" href="#">資訊學院</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#">資訊管理系</a>
                                <a class="dropdown-item" href="#">資訊工程系</a>
                                <a class="dropdown-item" href="#">資訊與通訊系</a>
                            </td>
                            <td>
                                <a class="dropdown-item" href="#">通識教育</a>
                            </td>
                        </table>
                    </div>
                </div>
                <div class="btn-group col px-0">
                    <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">物品</button>
                    <div class="dropdown-menu w-100">
                        <a class="dropdown-item" href="#">Tablet</a>
                        <a class="dropdown-item" href="#">Smartphone</a>
                    </div>
                </div>
                <div class="btn-group col px-0">
                    <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">共享</button>
                    <div class="dropdown-menu w-100">
                        <a class="dropdown-item" href="#">Tablet</a>
                        <a class="dropdown-item" href="#">Smartphone</a>
                    </div>
                </div>
                <div class="btn-group col px-0">
                    <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">我的商品</button>
                    <div class="dropdown-menu w-100">
                        <a class="dropdown-item" href="#">Tablet</a>
                        <a class="dropdown-item" href="#">Smartphone</a>
                    </div>
                </div>
                <div class="btn-group col px-0">
                    <h:link class="btn btn-primary" outcome="/member/searchBook">尋書</h:link>
                </div>
            </div>
        </ui:composition>
    </h:body>
</html>

group_A_subproject/BookEntryBean/src/main/webapp/templates/header.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        <ui:composition>
            <header>
                <div class="row">
                    <div class="col-12">
                        <div class="box">
                            <div class="container-4">
                                <nav class="navbar navbar-light bg-light">
                                    <a class="navbar-brand"><img src="imges/log.jpg" class="rounded float-left" alt="LOGO"/></a>
                                    <form class="form-inline">
                                        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search"/>
                                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                                        <h:link outcome="/member/member.xhtml" class="btn btn-primary btn-sm">會員專區</h:link>
                                        <h:link outcome="/authen/login" class="btn btn-primary btn-sm">登入/註冊</h:link>
                                        <a class="btn btn-primary btn-sm" href="#" role="button">收藏</a>
                                    </form>
                                </nav>  
                            </div>            
                        </div>  
                    </div>
                </div>
            </header>
        </ui:composition>
    </h:body>
</html>

group_A_subproject/BookEntryBean/src/main/webapp/templates/masterTemplate.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <h:head>
        <title>#{pageTitle}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"/>
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous"/>
        <h:outputScript library="primefaces" name="jquery/jquery.js" />
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>

    </h:head>

    <h:body>
        <ui:insert name="globalArea">
            <ui:include src="globalNavBar.xhtml"/>
        </ui:insert>

        <div class="container-fluid">
            <ui:insert name="content"/>
        </div>
    </h:body>
</html>

group_A_subproject/BookEntryBean/src/main/webapp/templates/memberAreaLayout.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        <ui:composition>
            <div class="row">
                <div class="col-md-3 border-right" align="center">
                    <ul class="list-group">
                        <h1>會員專區</h1>
                        <!--Done Note. 已設定 outcome 屬性, 套用 text-primary class, 方便區別.
                            @hychen39, Sp4.
                        -->
                        <h:link id="account_basic"
                            class="list-group-item list-group-item-action text-primary"
                            outcome="personalData">
                            基本資料
                        </h:link>
                        <h:link class="list-group-item list-group-item-action">我的收藏</h:link>
                        <!--Done: 加入購買記錄的連結 @hychen39, sp4-->
                        <h:link class="list-group-item list-group-item-action text-primary"
                                outcome="orders">
                            購買紀錄
                        </h:link>
                        <br/>
                        <h:link 
                            class="list-group-item list-group-item-action">
                            銷售紀錄</h:link>
                        <h:link class="list-group-item list-group-item-action text-primary" outcome="member">我的商品</h:link>
                        <br/>
                        <h:link class="list-group-item list-group-item-action">我的筆記</h:link>
                    </ul>
                </div>
                <div class="col-md-9">
                    <ui:insert name="member_content">
                    </ui:insert>
                </div>
            </div>
        </ui:composition>
    </h:body>
</html>